# Generated by Django 2.1.7 on 2019-12-14 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0010_auto_20190326_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmcontestrank',
            name='frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='acmcontestrank',
            unique_together={('user', 'contest', 'frozen')},
        ),
    ]
