# Generated by Django 2.1.7 on 2019-12-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_auto_20191214_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='frozen',
            field=models.BooleanField(default=False),
        ),
    ]
